<?php
namespace Database\Factories\Davidiwezulu\Ecommerce\Models;

use Illuminate\Database\Eloquent\Factories\Factory;
use Davidiwezulu\Ecommerce\Models\Inventory;

/**
 * Class InventoryFactory
 *
 * Factory definition for the Inventory model. This factory generates fake data
 * to facilitate testing and seeding of inventory records within the e-commerce system.
 * The factory allows the creation of Inventory model instances with random or pre-defined values.
 *
 * @package    Database\Factories\Davidiwezulu\Ecommerce\Models
 * @subpackage InventoryFactory
 * @category   Factory
 * @license    MIT
 * @link       https://davidiwezulu.co.uk/documentation
 */
class InventoryFactory extends Factory
{
    /**
     * The name of the factory's corresponding model.
     *
     * @var string
     */
    protected $model = Inventory::class;

    /**
     * Define the model's default state.
     *
     * This method returns an array of default attributes that will be applied
     * to each Inventory instance generated by the factory.
     *
     * @return array
     */
    public function definition(): array
    {
        return [
            'product_id' => null, // Will be set when associated with a product
            'quantity' => $this->faker->numberBetween(10, 100), // Random inventory quantity between 10 and 100
        ];
    }
}
